// Generated by ProxyPESourceGenerator

#pragma once
#include <Windows.h>

extern LPCSTR libraryFilePath;
extern SIZE_T symbolCount;
extern FARPROC symbolAddressArray[];
extern LPCSTR symbolNameArray[];
